# Generated by Django 4.2.19 on 2025-06-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название меню')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный идентификатор')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок пункта')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('named_url', models.CharField(blank=True, max_length=100, verbose_name='Именованная ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
